server:
    port: 8082
    error:
        whitelabel:
            enabled: false

spring:
    jmx:
        enabled: true
    data:
        mongodb:
            url: localhost:27017/mutant

---

spring:
    profiles: test

---

spring:
    profiles: stag

sentry:
    dns: "${sentry-path}"

---

spring:
    profiles: prod

ehcache:
    heap-size: 512

sentry:
    dns: "${sentry-path}"
