server:
    port: 8082
    error:
        whitelabel:
            enabled: false

spring:
    jmx:
        enabled: true
    data:
        mongodb:
            url: ds053126.mlab.com:53126/heroku_1fccdwbd
            username: andrey.justo
            password: mutant_test

---

spring:
    profiles: test

---

spring:
    profiles: stag

sentry:
    dns: "${sentry-path}"

---

spring:
    profiles: prod

ehcache:
    heap-size: 512

sentry:
    dns: "${sentry-path}"
