service: default

runtime: java
env: flex

handlers:
- url: /.*
  script: this field is required, but ignored

runtime_config:  # Optional
  jdk: openjdk8

manual_scaling:
  instances: 1


health_check:
  enable_health_check: False
